[package]
name = "kos-crypto"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
kos-types = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
wasm-bindgen = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }
coins-bip32 = { workspace = true }
coins-bip39 = { workspace = true }
hex = { workspace = true }
sha1 = "0.10"
sha2 = { workspace = true }
sha3 = { workspace = true }
hmac = { workspace = true }
secp256k1 = { workspace = true, features = ["rand", "serde", "bitcoin_hashes"] }
ed25519-dalek = { workspace = true, features = ["serde"]  }
aes-gcm = "0.10"
aes = { version = "0.8" }
cfb-mode = "0.8"
cbc = { version = "0.1", features = ["block-padding", "std"] }
pem = "3"
pbkdf2 = { version = "0.12", features = ["simple"] }
base64 = "0.21"
subxt-signer = "0.30.1"
